CREATE USER C##DAM2 IDENTIFIED BY password;

GRANT CONNECT, RESOURCE TO C##DAM2;

GRANT
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE
TO C##DAM2;

ALTER USER C##DAM2 QUOTA UNLIMITED ON USERS;

