INSERT INTO PRODUCTOS (ID, NOMBRE, STOCK) VALUES (1, 'Teclado Mecánico', 50);
INSERT INTO PRODUCTOS (ID, NOMBRE, STOCK) VALUES (2, 'Mouse Óptico', 120);
INSERT INTO PRODUCTOS (ID, NOMBRE, STOCK) VALUES (3, 'Monitor 24\"', 30);
