CREATE USER DAM2 IDENTIFIED BY password;

GRANT CONNECT, RESOURCE TO DAM2;

GRANT
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE SESSION,
  CREATE PROCEDURE
TO DAM2;

ALTER USER DAM2 QUOTA UNLIMITED ON USERS;

